name: CD

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v4.2.2
        with:
          distribution: 'temurin'
          java-version: '22'
      - name: Setup Android SDK Tools
        uses: android-actions/setup-android@v3.2.1
      - name: Build with Gradle
        run: gradle build -p ./App
        env:
          TRELLO_API_KEY: ${{secrets.TRELLO_API_KEY}}
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "App/app/build/outputs/apk/debug/*.apk"
          tag: "debug"
