name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    # branches: [ "main" ]
    branches: ["*"]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Source
        uses: actions/checkout@v4
      - run: ls $GITHUB_WORKSPACE
      - name: Setup JDK
        uses: actions/setup-java@v4.2.2
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Download dependencies
        run: ./gradlew dependencies
      - name: Build with Gradle
        run: $GITHUB_WORKSPACE/gradlew build
      - name: Release
        uses: fnkr/github-action-ghr@v1.3
        env:
          GHR_PATH: build/outputs/apk/debug
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
