name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    # branches: [ "main" ]
    branches: ["*"]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v4.2.2
        with:
          distribution: 'temurin'
          java-version: '22'
      - name: Setup Android SDK Tools
        uses: android-actions/setup-android@v3.2.1
      - name: Build with Gradle
        run: gradle build -p ./App
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "App/app/build/outputs/apk/debug/*.apk"
          tag: $(date +'%Y-%m-%d')
