name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    # branches: [ "main" ]
    branches: ["*"]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - uses: gradle/gradle-build-action@v3.5.0
      - name: Release
        uses: fnkr/github-action-ghr@v1.3
        env:
          GHR_PATH: build/outputs/apk/debug
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
